services:
  - type: web
    name: bookengin
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: FISH_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bookengin-db
          property: connectionString

  - type: pserv
    name: bookengin-db
    plan: free
    region: oregon
